// ============================================================
// Weighted skill / keyword dictionary
// Maps normalized terms → { category, weight }
// Higher weight = more important for match scoring
// ============================================================

import type { TokenCategory } from "./types";

interface SkillEntry {
  category: TokenCategory;
  weight: number;
}

/** Curated dictionary of weighted skills, tools, and terms. */
export const SKILL_WEIGHTS: Record<string, SkillEntry> = {
  // ── Programming Languages ──────────────────────────────────
  javascript:    { category: "programming_language", weight: 2.5 },
  typescript:    { category: "programming_language", weight: 2.5 },
  python:        { category: "programming_language", weight: 2.5 },
  java:          { category: "programming_language", weight: 2.5 },
  "c++":         { category: "programming_language", weight: 2.5 },
  "c#":          { category: "programming_language", weight: 2.5 },
  csharp:        { category: "programming_language", weight: 2.5 },
  go:            { category: "programming_language", weight: 2.5 },
  golang:        { category: "programming_language", weight: 2.5 },
  rust:          { category: "programming_language", weight: 2.5 },
  ruby:          { category: "programming_language", weight: 2.5 },
  php:           { category: "programming_language", weight: 2.5 },
  swift:         { category: "programming_language", weight: 2.5 },
  kotlin:        { category: "programming_language", weight: 2.5 },
  scala:         { category: "programming_language", weight: 2.5 },
  r:             { category: "programming_language", weight: 2.5 },
  matlab:        { category: "programming_language", weight: 2.5 },
  perl:          { category: "programming_language", weight: 2.0 },
  lua:           { category: "programming_language", weight: 2.0 },
  dart:          { category: "programming_language", weight: 2.5 },
  elixir:        { category: "programming_language", weight: 2.0 },
  haskell:       { category: "programming_language", weight: 2.0 },
  sql:           { category: "programming_language", weight: 2.5 },
  html:          { category: "programming_language", weight: 2.0 },
  css:           { category: "programming_language", weight: 2.0 },
  sass:          { category: "programming_language", weight: 2.0 },
  scss:          { category: "programming_language", weight: 2.0 },
  bash:          { category: "programming_language", weight: 2.0 },
  shell:         { category: "programming_language", weight: 2.0 },
  powershell:    { category: "programming_language", weight: 2.0 },
  solidity:      { category: "programming_language", weight: 2.5 },

  // ── Frameworks & Libraries ─────────────────────────────────
  react:         { category: "framework", weight: 2.5 },
  reactjs:       { category: "framework", weight: 2.5 },
  "react.js":    { category: "framework", weight: 2.5 },
  nextjs:        { category: "framework", weight: 2.5 },
  "next.js":     { category: "framework", weight: 2.5 },
  angular:       { category: "framework", weight: 2.5 },
  vue:           { category: "framework", weight: 2.5 },
  vuejs:         { category: "framework", weight: 2.5 },
  "vue.js":      { category: "framework", weight: 2.5 },
  svelte:        { category: "framework", weight: 2.5 },
  nuxt:          { category: "framework", weight: 2.0 },
  "nuxt.js":     { category: "framework", weight: 2.0 },
  gatsby:        { category: "framework", weight: 2.0 },
  remix:         { category: "framework", weight: 2.0 },
  express:       { category: "framework", weight: 2.5 },
  "express.js":  { category: "framework", weight: 2.5 },
  nestjs:        { category: "framework", weight: 2.5 },
  fastapi:       { category: "framework", weight: 2.5 },
  django:        { category: "framework", weight: 2.5 },
  flask:         { category: "framework", weight: 2.5 },
  "ruby on rails": { category: "framework", weight: 2.5 },
  rails:         { category: "framework", weight: 2.5 },
  laravel:       { category: "framework", weight: 2.5 },
  "spring boot": { category: "framework", weight: 2.5 },
  spring:        { category: "framework", weight: 2.5 },
  ".net":        { category: "framework", weight: 2.5 },
  dotnet:        { category: "framework", weight: 2.5 },
  flutter:       { category: "framework", weight: 2.5 },
  "react native": { category: "framework", weight: 2.5 },
  tailwind:      { category: "framework", weight: 2.0 },
  tailwindcss:   { category: "framework", weight: 2.0 },
  "tailwind css": { category: "framework", weight: 2.0 },
  bootstrap:     { category: "framework", weight: 1.5 },
  jquery:        { category: "framework", weight: 1.5 },
  redux:         { category: "framework", weight: 2.0 },
  graphql:       { category: "framework", weight: 2.0 },
  "socket.io":   { category: "framework", weight: 2.0 },
  tensorflow:    { category: "framework", weight: 2.5 },
  pytorch:       { category: "framework", weight: 2.5 },
  keras:         { category: "framework", weight: 2.0 },
  pandas:        { category: "framework", weight: 2.0 },
  numpy:         { category: "framework", weight: 2.0 },
  scikit:        { category: "framework", weight: 2.0 },
  "scikit-learn": { category: "framework", weight: 2.0 },
  opencv:        { category: "framework", weight: 2.0 },
  hadoop:        { category: "framework", weight: 2.0 },
  spark:         { category: "framework", weight: 2.5 },
  kafka:         { category: "framework", weight: 2.5 },

  // ── DevOps / Tools ─────────────────────────────────────────
  docker:        { category: "tool", weight: 2.5 },
  kubernetes:    { category: "tool", weight: 2.5 },
  k8s:           { category: "tool", weight: 2.5 },
  terraform:     { category: "tool", weight: 2.5 },
  ansible:       { category: "tool", weight: 2.0 },
  jenkins:       { category: "tool", weight: 2.0 },
  git:           { category: "tool", weight: 2.0 },
  github:        { category: "tool", weight: 1.5 },
  gitlab:        { category: "tool", weight: 1.5 },
  bitbucket:     { category: "tool", weight: 1.5 },
  jira:          { category: "tool", weight: 1.5 },
  confluence:    { category: "tool", weight: 1.5 },
  figma:         { category: "tool", weight: 2.0 },
  webpack:       { category: "tool", weight: 2.0 },
  vite:          { category: "tool", weight: 2.0 },
  npm:           { category: "tool", weight: 1.5 },
  yarn:          { category: "tool", weight: 1.5 },
  pnpm:          { category: "tool", weight: 1.5 },
  postman:       { category: "tool", weight: 1.5 },
  swagger:       { category: "tool", weight: 1.5 },
  nginx:         { category: "tool", weight: 2.0 },
  apache:        { category: "tool", weight: 1.5 },
  linux:         { category: "tool", weight: 2.0 },
  unix:          { category: "tool", weight: 2.0 },
  elasticsearch: { category: "tool", weight: 2.0 },
  kibana:        { category: "tool", weight: 1.5 },
  grafana:       { category: "tool", weight: 1.5 },
  prometheus:    { category: "tool", weight: 1.5 },
  datadog:       { category: "tool", weight: 1.5 },
  splunk:        { category: "tool", weight: 1.5 },
  sentry:        { category: "tool", weight: 1.5 },
  vercel:        { category: "tool", weight: 2.0 },
  netlify:       { category: "tool", weight: 1.5 },
  heroku:        { category: "tool", weight: 1.5 },

  // ── Cloud ──────────────────────────────────────────────────
  aws:           { category: "cloud", weight: 2.5 },
  "amazon web services": { category: "cloud", weight: 2.5 },
  azure:         { category: "cloud", weight: 2.5 },
  gcp:           { category: "cloud", weight: 2.5 },
  "google cloud": { category: "cloud", weight: 2.5 },
  s3:            { category: "cloud", weight: 2.0 },
  ec2:           { category: "cloud", weight: 2.0 },
  lambda:        { category: "cloud", weight: 2.0 },
  cloudfront:    { category: "cloud", weight: 1.5 },
  cloudflare:    { category: "cloud", weight: 1.5 },
  firebase:      { category: "cloud", weight: 2.0 },
  supabase:      { category: "cloud", weight: 2.0 },

  // ── Databases ──────────────────────────────────────────────
  mysql:         { category: "database", weight: 2.5 },
  postgresql:    { category: "database", weight: 2.5 },
  postgres:      { category: "database", weight: 2.5 },
  mongodb:       { category: "database", weight: 2.5 },
  redis:         { category: "database", weight: 2.5 },
  sqlite:        { category: "database", weight: 2.0 },
  dynamodb:      { category: "database", weight: 2.0 },
  cassandra:     { category: "database", weight: 2.0 },
  neo4j:         { category: "database", weight: 2.0 },
  oracle:        { category: "database", weight: 2.0 },
  couchdb:       { category: "database", weight: 1.5 },
  firestore:     { category: "database", weight: 2.0 },
  prisma:        { category: "database", weight: 2.0 },
  sequelize:     { category: "database", weight: 1.5 },
  mongoose:      { category: "database", weight: 1.5 },

  // ── Methodologies & Practices ──────────────────────────────
  agile:         { category: "methodology", weight: 1.5 },
  scrum:         { category: "methodology", weight: 1.5 },
  kanban:        { category: "methodology", weight: 1.5 },
  "ci/cd":       { category: "methodology", weight: 2.0 },
  cicd:          { category: "methodology", weight: 2.0 },
  devops:        { category: "methodology", weight: 2.0 },
  microservices: { category: "methodology", weight: 2.0 },
  "micro-services": { category: "methodology", weight: 2.0 },
  restful:       { category: "methodology", weight: 2.0 },
  rest:          { category: "methodology", weight: 2.0 },
  api:           { category: "methodology", weight: 2.0 },
  apis:          { category: "methodology", weight: 2.0 },
  tdd:           { category: "methodology", weight: 1.5 },
  bdd:           { category: "methodology", weight: 1.5 },
  "unit testing": { category: "methodology", weight: 1.5 },
  "test driven":  { category: "methodology", weight: 1.5 },
  oop:           { category: "methodology", weight: 1.5 },
  "object oriented": { category: "methodology", weight: 1.5 },
  "design patterns": { category: "methodology", weight: 1.5 },
  "machine learning": { category: "methodology", weight: 2.5 },
  "deep learning":    { category: "methodology", weight: 2.5 },
  "data science":     { category: "methodology", weight: 2.5 },
  "data engineering":  { category: "methodology", weight: 2.5 },
  "data analysis":     { category: "methodology", weight: 2.0 },
  "data analytics":    { category: "methodology", weight: 2.0 },
  "natural language processing": { category: "methodology", weight: 2.5 },
  nlp:           { category: "methodology", weight: 2.5 },
  "computer vision":   { category: "methodology", weight: 2.5 },
  blockchain:    { category: "methodology", weight: 2.0 },
  cybersecurity: { category: "methodology", weight: 2.0 },
  "web development":   { category: "methodology", weight: 1.5 },
  "full stack":        { category: "methodology", weight: 2.0 },
  fullstack:     { category: "methodology", weight: 2.0 },
  "full-stack":  { category: "methodology", weight: 2.0 },
  frontend:      { category: "methodology", weight: 2.0 },
  "front-end":   { category: "methodology", weight: 2.0 },
  backend:       { category: "methodology", weight: 2.0 },
  "back-end":    { category: "methodology", weight: 2.0 },
  responsive:    { category: "methodology", weight: 1.5 },
  accessibility: { category: "methodology", weight: 1.5 },
  seo:           { category: "methodology", weight: 1.5 },
  performance:   { category: "methodology", weight: 1.5 },
  optimization:  { category: "methodology", weight: 1.5 },
  scalability:   { category: "methodology", weight: 1.5 },
  architecture:  { category: "methodology", weight: 1.5 },
  "system design": { category: "methodology", weight: 2.0 },

  // ── Soft Skills ────────────────────────────────────────────
  leadership:    { category: "soft_skill", weight: 1.0 },
  communication: { category: "soft_skill", weight: 1.0 },
  collaboration: { category: "soft_skill", weight: 1.0 },
  teamwork:      { category: "soft_skill", weight: 1.0 },
  "problem solving": { category: "soft_skill", weight: 1.0 },
  "problem-solving": { category: "soft_skill", weight: 1.0 },
  analytical:    { category: "soft_skill", weight: 1.0 },
  creative:      { category: "soft_skill", weight: 1.0 },
  innovative:    { category: "soft_skill", weight: 1.0 },
  proactive:     { category: "soft_skill", weight: 1.0 },
  mentoring:     { category: "soft_skill", weight: 1.0 },
  mentorship:    { category: "soft_skill", weight: 1.0 },

  // ── Role / Seniority Terms ─────────────────────────────────
  senior:        { category: "role", weight: 1.5 },
  junior:        { category: "role", weight: 1.5 },
  lead:          { category: "role", weight: 1.5 },
  principal:     { category: "role", weight: 1.5 },
  staff:         { category: "role", weight: 1.5 },
  manager:       { category: "role", weight: 1.5 },
  director:      { category: "role", weight: 1.5 },
  architect:     { category: "role", weight: 1.5 },
  intern:        { category: "role", weight: 1.5 },
  associate:     { category: "role", weight: 1.5 },

  // ── Education ──────────────────────────────────────────────
  "bachelor's":  { category: "education", weight: 1.5 },
  bachelors:     { category: "education", weight: 1.5 },
  "master's":    { category: "education", weight: 1.5 },
  masters:       { category: "education", weight: 1.5 },
  phd:           { category: "education", weight: 1.5 },
  doctorate:     { category: "education", weight: 1.5 },
  mba:           { category: "education", weight: 1.5 },
  "computer science": { category: "education", weight: 1.5 },
  "information technology": { category: "education", weight: 1.5 },
  engineering:   { category: "education", weight: 1.5 },
  mathematics:   { category: "education", weight: 1.5 },
  statistics:    { category: "education", weight: 1.5 },

  // ── Certifications ─────────────────────────────────────────
  "aws certified": { category: "certification", weight: 2.0 },
  "azure certified": { category: "certification", weight: 2.0 },
  "google certified": { category: "certification", weight: 2.0 },
  pmp:           { category: "certification", weight: 1.5 },
  "scrum master": { category: "certification", weight: 1.5 },
  cissp:         { category: "certification", weight: 1.5 },
  comptia:       { category: "certification", weight: 1.5 },
};
