// ============================================================
// English stopword list — common words to filter out
// ============================================================

export const STOPWORDS = new Set([
  // Articles & determiners
  "a", "an", "the", "this", "that", "these", "those",
  // Pronouns
  "i", "me", "my", "myself", "we", "our", "ours", "ourselves",
  "you", "your", "yours", "yourself", "yourselves",
  "he", "him", "his", "himself", "she", "her", "hers", "herself",
  "it", "its", "itself", "they", "them", "their", "theirs", "themselves",
  // Prepositions
  "in", "on", "at", "to", "for", "of", "with", "by", "from",
  "up", "about", "into", "through", "during", "before", "after",
  "above", "below", "between", "under", "over", "out", "off",
  "against", "within", "along", "across", "around", "among",
  // Conjunctions
  "and", "but", "or", "nor", "so", "yet", "both", "either",
  "neither", "not", "only", "than", "when", "while", "if",
  "because", "since", "although", "though", "unless", "until",
  // Common verbs / auxiliaries
  "is", "am", "are", "was", "were", "be", "been", "being",
  "have", "has", "had", "having", "do", "does", "did", "doing",
  "will", "would", "shall", "should", "may", "might", "must",
  "can", "could",
  // Adverbs / misc
  "very", "just", "also", "then", "now", "here", "there",
  "where", "how", "all", "each", "every", "any", "few",
  "more", "most", "other", "some", "such", "no", "own",
  "same", "too", "as", "well", "what", "which", "who",
  "whom", "whose", "why",
  // Common resume / JD filler words
  "etc", "eg", "ie", "via", "per", "using", "used", "use",
  "able", "ability", "including", "include", "includes",
  "work", "working", "worked", "works",
  "experience", "experienced", "experiences",
  "ensure", "ensuring", "ensures",
  "provide", "providing", "provides", "provided",
  "support", "supporting", "supports", "supported",
  "help", "helping", "helps", "helped",
  "need", "needed", "needs",
  "require", "required", "requires", "requirements", "requirement",
  "develop", "developing", "developed", "develops",
  "create", "creating", "created", "creates",
  "manage", "managing", "managed", "manages",
  "build", "building", "built", "builds",
  "maintain", "maintaining", "maintained", "maintains",
  "implement", "implementing", "implemented", "implements",
  "make", "making", "made", "makes",
  "take", "taking", "taken", "takes",
  "get", "getting", "got", "gets",
  "set", "setting", "sets",
  "look", "looking", "looked", "looks",
  "find", "finding", "found", "finds",
  "give", "giving", "gave", "gives",
  "tell", "telling", "told", "tells",
  "know", "knowing", "knew", "knows",
  "come", "coming", "came", "comes",
  "think", "thinking", "thought", "thinks",
  "see", "seeing", "saw", "sees",
  "want", "wanting", "wanted", "wants",
  "put", "putting", "puts",
  "run", "running", "ran", "runs",
  "keep", "keeping", "kept", "keeps",
  "let", "letting", "lets",
  "begin", "beginning", "began", "begins",
  "show", "showing", "showed", "shows",
  "try", "trying", "tried", "tries",
  "ask", "asking", "asked", "asks",
  "move", "moving", "moved", "moves",
  "play", "playing", "played", "plays",
  "turn", "turning", "turned", "turns",
  "start", "starting", "started", "starts",
  "open", "opening", "opened", "opens",
  "close", "closing", "closed", "closes",
  "read", "reading", "reads",
  "write", "writing", "wrote", "writes",
  // Common filler
  "new", "good", "great", "best", "better", "strong",
  "high", "low", "big", "small", "large", "long", "short",
  "old", "young", "right", "left", "first", "last", "next",
  "day", "time", "year", "years", "team", "teams",
  "role", "join", "part", "full", "company", "organization",
  "position", "opportunity", "opportunities", "candidate",
  "candidates", "apply", "application", "applications",
  "job", "jobs", "ideal", "passionate", "plus", "bonus",
  "preferred", "desired", "relevant", "related",
  "minimum", "maximum", "least", "must", "shall",
  "responsible", "responsibilities", "responsibility",
  "key", "based", "across", "well", "like",
]);
